name: ✨ Новая возможность | Feature Request
description: Предложить идею или улучшение для проекта | Suggest a new idea for this project
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    attributes:
      label: Описание потребности | Problem Statement
      description: |
        Опишите проблему или потребность, которую хотите закрыть 
        Please describe the problem you want to solve
      placeholder: |
        В процессе использования я столкнулся с...
        I encountered... when using this project
    validations:
      required: true
  - type: textarea
    attributes:
      label: Предлагаемое решение | Proposed Solution
      description: |
        Опишите решение или способ реализации, который считаете подходящим
        Please describe your suggested solution or implementation
      placeholder: |
        Можно добавить возможность..., чтобы решить эту задачу
        Consider adding... feature to address this issue
    validations:
      required: true